const imgList = {
  0: '<img src="images/game_1.png" alt="">',
  1: '<img src="images/game_2.png" alt="">',
  2: '<img src="images/game_3.png" alt="">',
  3: '<img src="images/game_4.png" alt="">',
  4: '<img src="images/game_5.png" alt="">',
  5: '<img src="images/game_6.png" alt="">',
  6: '<img src="images/game_7.png" alt="">',
  7: '<img src="images/game_8.png" alt="">',
  8: '<img src="images/game_9.jpg" alt="">',
  9: '<img src="images/game_10.jpg" alt="">',
  10: '<img src="images/game_11.jpg" alt="">',
  11: '<img src="images/game_12.jpg" alt="">',
  12: '<img src="images/game_13.jpg" alt="">',
  13: '<img src="images/game_14.jpg" alt="">',
  14: '<img src="images/game_15.jpg" alt="">',
  15: '<img src="images/game_16.jpg" alt="">',
  16: '<img src="images/game_17.jpg" alt="">',
  17: '<img src="images/game_18.jpg" alt="">',
  18: '<img src="images/game_19.jpg" alt="">',
  19: '<img src="images/game_20.jpg" alt="">',
  20: '<img src="images/game_21.jpg" alt="">',
  21: '<img src="images/game_22.jpg" alt="">',
  22: '<img src="images/game_23.jpg" alt="">',
  23: '<img src="images/game_24.jpg" alt="">',
  24: '<img src="images/game_25.jpg" alt="">',
  25: '<img src="images/game_26.jpg" alt="">',
  26: '<img src="images/game_27.jpg" alt="">',
  27: '<img src="images/game_28.jpg" alt="">',
  28: '<img src="images/game_29.png" alt="">',
  29: '<img src="images/game_30.png" alt="">',
  30: '<img src="images/game_31.png" alt="">',
  31: '<img src="images/game_32.png" alt="">',
  32: '<img src="images/game_33.png" alt="">',
  33: '<img src="images/game_34.png" alt="">',
  34: '<img src="images/game_35.png" alt="">',
  35: '<img src="images/game_36.png" alt="">',
  36: '<img src="images/game_37.png" alt="">',
  37: '<img src="images/game_38.png" alt="">',
  38: '<img src="images/game_39.png" alt="">',
  39: '<img src="images/game_40.png" alt="">',
  40: '<img src="images/game_41.png" alt="">',
  41: '<img src="images/game_42.png" alt="">',
  42: '<img src="images/game_43.png" alt="">',
  43: '<img src="images/game_44.png" alt="">',
  44: '<img src="images/game_45.png" alt="">',
  45: '<img src="images/game_46.png" alt="">',
  46: '<img src="images/game_47.png" alt="">',
  47: '<img src="images/game_48.png" alt="">',
  48: '<img src="images/game_49.png" alt="">',
  49: '<img src="images/game_50.png" alt="">',
  50: '<img src="images/game_51.png" alt="">',
  51: '<img src="images/game_52.png" alt="">',
  52: '<img src="images/game_53.png" alt="">',
  53: '<img src="images/game_54.png" alt="">',
  54: '<img src="images/game_55.png" alt="">',
  55: '<img src="images/game_56.png" alt="">',
  56: '<img src="images/game_57.png" alt="">',
  57: '<img src="images/game_58.png" alt="">',
  58: '<img src="images/game_59.png" alt="">',
  59: '<img src="images/game_60.png" alt="">',
  60: '<img src="images/game_61.png" alt="">',
  61: '<img src="images/game_62.png" alt="">',
  62: '<img src="images/game_63.png" alt="">',
  63: '<img src="images/game_64.png" alt="">',
  64: '<img src="images/game_65.png" alt="">',
  65: '<img src="images/game_66.png" alt="">',
  66: '<img src="images/game_67.png" alt="">',
  67: '<img src="images/game_68.png" alt="">',
  68: '<img src="images/game_69.png" alt="">',
  69: '<img src="images/game_70.png" alt="">',
  70: '<img src="images/game_71.png" alt="">',
  71: '<img src="images/game_72.png" alt="">',
  72: '<img src="images/game_73.png" alt="">',
  73: '<img src="images/game_74.png" alt="">',
  74: '<img src="images/game_75.png" alt="">',
  75: '<img src="images/game_76.png" alt="">',
  76: '<img src="images/game_77.png" alt="">',
  77: '<img src="images/game_78.png" alt="">'
}

const h4List = {
  0: '니모의 오션라이프',
  1: '바람의나라: 연',
  2: '메이플스토리M',
  3: '앨리스클로젯',
  4: '그랑사가',
  5: '프렌즈레이싱 듀오',
  6: '리얼퍼즐쾌감! 우주스타의 액션퍼즐게임',
  7: '엘더스크롤: 블레이드',
  8: '가디언 테일즈',
  9: '애니팡4',
  10: '디즈니 팝 타운',
  11: '달빛조각사',
  12: '테라 클래식',
  13: '쿵야 캐치마인드',
  14: '프렌즈타운',
  15: '프린세스 커넥트! Re:Dive',
  16: '외모지상주의',
  17: '창세기전 : 안타리아의 전쟁',
  18: '프렌즈레이싱',
  19: '신사조영웅전',
  20: '아이러브마트',
  21: '프렌즈타워',
  22: '캔디팡 : 쥬시월드',
  23: '헬로히어로 에픽배틀: 3D RPG',
  24: '블레이드2',
  25: '낚시왕',
  26: '윈드러너Z',
  27: '넛잡',
  28: '뱅드림! 걸즈 밴드 파티!',
  29: '그랜드체이스',
  30: '헬로키티 프렌즈',
  31: '위 베어 베어스 더 퍼즐',
  32: '프렌즈마블',
  33: '활2',
  34: '스누피 틀린그림찾기',
  35: '열혈강호',
  36: '아이러브판타지',
  37: '전함제국',
  38: '원카드',
  39: '스튜어디스 타이쿤',
  40: '피망 섯다',
  41: '피망 뉴맞고',
  42: '에브리타운 스윗',
  43: '마이리틀셰프',
  44: '펜타스톰',
  45: '얼터너티브 걸즈2',
  46: '여명',
  47: '의천도룡기',
  48: '로드오브다이스',
  49: '뚱팡',
  50: '애니팡 섯다',
  51: '퍼즐쓰리고',
  52: '초월',
  53: '애니팡 터치',
  54: '헬로씨푸드2',
  55: '데스티니차일드',
  56: '프렌즈팝콘',
  57: '애니팡3',
  58: '한방맞고',
  59: '구음진경',
  60: '프렌즈사천성',
  61: '놀러와 마이홈',
  62: '애니팡 포커',
  63: '피망 포커',
  64: '아이러브니키',
  65: '촉산',
  66: '검과마법',
  67: '드림스쿼드',
  68: '배틀캐논',
  69: '아이러브버거',
  70: '아이러브쇼핑',
  71: '바둑:승부의신',
  72: '바둑2.0',
  73: '조이플래닛',
  74: '마이리틀팜',
  75: '인생역전윷놀이',
  76: '애니팡 맞고',
  77: '장기 2.0'
}

const p1List = {
  0: '니모를 찾아서의 감동이 모바일로 풍덩!',
  1: '넥슨은 다람쥐를 뿌려라! 바~람↗의-나↘라~바람의→나라 모바일로 등장!',
  2: '메이플스토리M',
  3: '♣당신이 사랑할, 앨리스클로젯♣',
  4: '위대한 전설의 시작! 그랑사가',
  5: '"어쩌면" 세계 최초 듀오 태그 레이싱게임 프렌즈레이싱 듀오!',
  6: '리얼퍼즐쾌감! 우주스타의 액션퍼즐게임',
  7: '오리지널 엘더스크롤 시리즈의 신작',
  8: '띵작 어드벤처 가디언테일즈',
  9: '다시 한 팡 붙자! 애니팡4!',
  10: '귀여움이 팝! 춤추는 타운! 꿈과 마법의 뮤지컬타운!',
  11: '모험가들의 꿈! 달빛조각사',
  12: '같지만 또 다른 세계, 테라 클래식!',
  13: '빵터지는 모바일 그림퀴즈 게임!',
  14: '퍼즐로 꾸미는 상상타운, 프렌즈타운!',
  15: "'소녀와 나'의 애니 RPG, 프린세스 커넥트! Re:Dive",
  16: '국민웹툰<외모지상주의> 이제, 게임으로 즐기세요!',
  17: '전략과 RPG를 완벽하게 넘나들다!',
  18: '프렌즈와 함께 밟아버려씽!',
  19: '2018년 최신 무협 MMORPG 모바일 게임 - <신사조영웅전!>!',
  20: '우리집 진짜 배송',
  21: '손 끝으로 그리는 퍼즐, 프렌즈타워',
  22: '이제 밀지말고 누르세요!',
  23: '49개국 1위! 원조가 돌아왔다!',
  24: '신규/복귀 유저 접속 시 10성 장비 풀세트 + 1억 골드 즉시 지급!',
  25: "본격 리얼 낚시 대전 '낚시왕'!!",
  26: '★접속하면 루비가 생길꺼야 아마두★',
  27: '내가 너무 귀여워도 나를 귀엽다고 하지마!!',
  28: '반짝반짝 두근두근 꿈의 라이브!',
  29: '차원을 넘어선 모험, 그랜드체이스!',
  30: '귀여운 산리오 캐릭터들이 퍼즐게임에 나타났다!',
  31: '신나는 퍼즐! 개성만점 곰 삼형제 이야기!',
  32: '손에 땅을 쥐는 재미, 프렌즈마블!',
  33: '실시간 액션 활투극!',
  34: '틀림없는 재미! 스누피 틀린그림찾기',
  35: '열혈강호 최초 모바일 MMORPG',
  36: '처음 만나는 판타지 경영!!',
  37: '글로벌 3천만 유저의 선택! 가장 완벽한 정통 해전 게임!',
  38: '세계 최초 팬 아트 카드 게임. 원카드로 나만의 테마 카드를 만들어보세요.',
  39: '모바일게임 최초의 스튜어디스 게임, 그녀들의 꿈과 사랑이 지금 화려하게 펼쳐집니다...',
  40: '진짜 손맛의 진수! 피망 섯다',
  41: '대한민국 1등 고스톱, 피망 뉴맞고',
  42: '세상에서 가장사랑스러운 퍼즐 게임',
  43: '별별맛 요리게임 - 마이리틀셰프에서 만나요!',
  44: '클론 격투! 신규 모드 오픈!',
  45: 'VR 대응 미소녀 RPG',
  46: '눈부신 MMORPG의 시작',
  47: '의천도룡기, 초대형 MMORRPG로 깨어난다!',
  48: '세상에 없던 전략 RPG',
  49: '궁디팡팡 뚱팡~!',
  50: '승부는 한끗 차이! 애니팡 섯다! 짜릿한 손맛을 경험해보세요.',
  51: '3매치 화투 퍼즐!',
  52: '온라인 게임을 초월한 무협대작: 초월 for Kakao!',
  53: '살짝꿍 Toc, 상큼함이 PANG!!',
  54: '대한민국 대표 레스토랑 경영 소셜 게임',
  55: '살짝 나쁜 모바일 RPG',
  56: '자꾸만 손이 가는 1등 퍼즐게임, 프렌즈팝콘:)',
  57: "국민게임 '애니팡'이 돌아왔다!",
  58: '★신봉선맞고 제작진의 화려한 컴백!!!★ ☆영국 맵 업데이트 완☆',
  59: '판에 박힌듯한 스킬패턴은 가라! 경공을 가미한 전투의 새로운 양상! 몇백개의 무공을...',
  60: '사천만을 이어 주는 연결고리, 프렌즈 사천성!',
  61: '너랑 나랑 만드는 달콤한 나의 공방',
  62: '리그를 리드하라! 애니팡 포커 시즌2 - 당신이 더욱 놀라워 할 판이 기다린다.',
  63: '대한민국 No1 하이클래스 포커, 피망포커',
  64: '#화제의신상#소장가치200%#스타일경쟁이시작되다',
  65: '시원한 가을 바람과 함게 다가온다! ◆9월 업데이트◆',
  66: '다시 만나는 세계',
  67: '세계가 인정한 풋볼 매니저! 카카오 상륙!',
  68: '전작을 뛰어넘는 통쾌한 타격감과 재미! 당신이 기다리던, 최고의 온라인 슈팅게임',
  69: '귀엽고 깜찍한 프렌차이즈',
  70: '내맘대로 쇼핑!! 세계 최초 쇼핑몰 게임!!',
  71: '★바둑리그 생중계!!★ 승자가 누가될지 미리 예측해 보세요.',
  72: '신개념 고품격 정통 바둑 게임',
  73: '내 손안에 펼쳐지는 세계여행!',
  74: '내 손안의 작은 농장 마이리틀팜',
  75: '새로운 판을 경험하라! 윷놀이 판에서 펼쳐지는 인생역전 스토리',
  76: '3천만이 즐긴 애니팡, 이제 애니팡 맞고로 만나보세요!',
  77: '어른들을 위한 고품격 정통 장기 게임'
}

const p2List = {
  0: '시뮬레이션',
  1: '롤플레잉',
  2: '롤플레잉',
  3: '시뮬레이션',
  4: '롤플레잉',
  5: '달리기',
  6: '퍼즐',
  7: '롤플레잉',
  8: '롤플레잉',
  9: '퍼즐',
  10: '퍼즐',
  11: '롤플레잉',
  12: '롤플레잉',
  13: '퀴즈',
  14: '퍼즐',
  15: '롤플레잉',
  16: '롤플레잉',
  17: '전략',
  18: '달리기',
  19: '롤플레잉',
  20: '시뮬레이션',
  21: '퍼즐',
  22: '퍼즐',
  23: '롤플레잉',
  24: '액션',
  25: '스포츠',
  26: '달리기',
  27: '퍼즐',
  28: '음악',
  29: '롤플레잉',
  30: '퍼즐',
  31: '퍼즐',
  32: '보드',
  33: '액션',
  34: '퍼즐',
  35: '롤플레잉',
  36: '시뮬레이션',
  37: '전략',
  38: '보드',
  39: '시뮬레이션',
  40: '보드',
  41: '보드',
  42: '퍼즐',
  43: '시뮬레이션',
  44: '액션',
  45: '롤플레잉',
  46: '롤플레잉',
  47: '롤플레잉',
  48: '롤플레잉',
  49: '퍼즐',
  50: '보드',
  51: '보드',
  52: '롤플레잉',
  53: '퍼즐',
  54: '시뮬레이션',
  55: '롤플레잉',
  56: '퍼즐',
  57: '퍼즐',
  58: '보드',
  59: '롤플레잉',
  60: '퍼즐',
  61: '시뮬레이션',
  62: '보드',
  63: '보드',
  64: '시뮬레이션',
  65: '롤플레잉',
  66: '롤플레잉',
  67: '스포츠',
  68: '슈팅',
  69: '시뮬레이션',
  70: '시뮬레이션',
  71: '보드',
  72: '보드',
  73: '퍼즐',
  74: '시뮬레이션',
  75: '보드',
  76: '보드',
  77: '보드'
}

const classList = {
  0: 'simulation',
  1: 'role-playing',
  2: 'role-playing',
  3: 'simulation',
  4: 'role-playing',
  5: 'run',
  6: 'puzzle',
  7: 'role-playing',
  8: 'role-playing',
  9: 'puzzle',
  10: 'puzzle',
  11: 'role-playing',
  12: 'role-playing',
  13: 'quiz',
  14: 'puzzle',
  15: 'role-playing',
  16: 'role-playing',
  17: 'strategy',
  18: 'run',
  19: 'role-playing',
  20: 'simulation',
  21: 'puzzle',
  22: 'puzzle',
  23: 'role-playing',
  24: 'action',
  25: 'sports',
  26: 'run',
  27: 'puzzle',
  28: 'music',
  29: 'role-playing',
  30: 'puzzle',
  31: 'puzzle',
  32: 'board',
  33: 'action',
  34: 'puzzle',
  35: 'role-playing',
  36: 'simulation',
  37: 'strategy',
  38: 'board',
  39: 'simulation',
  40: 'board',
  41: 'board',
  42: 'puzzle',
  43: 'simulation',
  44: 'action',
  45: 'role-playing',
  46: 'role-playing',
  47: 'role-playing',
  48: 'role-playing',
  49: 'puzzle',
  50: 'board',
  51: 'board',
  52: 'role-playing',
  53: 'puzzle',
  54: 'simulation',
  55: 'role-playing',
  56: 'puzzle',
  57: 'puzzle',
  58: 'board',
  59: 'role-playing',
  60: 'puzzle',
  61: 'simulation',
  62: 'board',
  63: 'board',
  64: 'simulation',
  65: 'role-playing',
  66: 'role-playing',
  67: 'sports',
  68: 'shooting',
  69: 'simulation',
  70: 'simulation',
  71: 'board',
  72: 'board',
  73: 'puzzle',
  74: 'simulation',
  75: 'board',
  76: 'board',
  77: 'board'
}

for (var i = 0; i < Object.keys(imgList).length; i++){
  const li = document.createElement('li');
  const h4 = document.createElement('h4');
  const p = document.createElement('p');
  const div = document.createElement('div');
  const p2 = document.createElement('p');

  li.innerHTML = imgList[i];
  li.className = classList[i];
  h4.append(h4List[i]);
  p.append(p1List[i]);

  p2.append(p2List[i]);
  div.innerHTML = '<img src="images/tag.png" alt="tag">';
  div.append(p2);  
  li.append(h4, p, div);
  
  const ul = document.getElementById("game_box");
  ul.appendChild(li);
}